### PR TITLE
1.0.6

### PR DESCRIPTION
**Pull request by Amxx**
I'd like to release the current version so we can move forward with testing in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3617

### CODE REVIEW

**Review by ernestognw — APPROVED** [review]
Yeah, let's merge this and continue with the MerkleTree builder PR

**Comment by frangio** [comment]
FYI, this repo is released manually via `npm version` + `npm publish`. Pushing the tag will create a GitHub release automatically.

**Comment by Amxx** [comment]
> FYI, this repo is released manually via `npm version` + `npm publish`. Pushing the tag will create a GitHub release automatically.

There is a security thing preventing me from pushing directly to master.

I wanted to do:
- nom version
- git push 
- npm publish
But step 2 was blocked and it did not feel right to publish a commit that is not on the master branch.

That is why I created this PR and planned to tag and publish the commit that result from this being merged. It that ok or should we do the release differently ?

**Comment by frangio** [comment]
Yes that sounds good!

**Pull request merged**
