### PR TITLE
update readme: update Standard Merkle Tree characteristics

### PR DESCRIPTION
**Pull request by gc-garcol**
In file core.ts

When building a merkle tree, that must be shaped of a full binary tree, so that we could calculate total tree nodes using formular: **2 * leaves.length - 1**

```
const tree = new Array<Bytes>(2 * leaves.length - 1);
```

### CODE REVIEW

**Comment by frangio** [comment]
This is not correct. The standard merkle trees produced by this library are not necessarily full.

**Comment by Amxx** [comment]
All binary trees have
- #internalNodes = #leaves - 1
- #nodes = #internalNodes + #leaves = 2 * #leaves - 1

It's not a property of full or complete tree. It can easily be proven by induction.

**Comment by gc-garcol** [comment]
> All binary trees have
> 
> * #internalNodes = #leaves - 1
> * #nodes = #internalNodes + #leaves = 2 * #leaves - 1
> 
> It's not a property of full or complete tree. It can easily be proven by induction.

Hi @Amxx, this is not correct.
Below is a example of a complete (but not full) binary tree (total leaves = 3 , total nodes = 6)

image

**Comment by Amxx** [comment]
That is not a binary tree. 3 has got only one child

**Comment by gc-garcol** [comment]
> That is not a binary tree. 3 has got only one child. Or maybe you are only showing the internal nodes and you have invisible (null) leafs.

@Amxx, you could find a definition of a binary tree here: https://en.wikipedia.org/wiki/Binary_tree

Below is a example of a binary tree (totalLeaves = 6, totalNodes = 12)

- https://en.wikipedia.org/wiki/Binary_tree#:~:text=A%20complete%20binary%20tree%20(that%20is%20not%20full)
- https://en.wikipedia.org/wiki/Binary_tree#/media/File:Complete_binary2.svg

**Comment by Amxx** [comment]
Binary tree look like this 


They are usually times:
```caml
type 'a binaryTree =
  | Nil
  | Node of 'a * 'a binaryTree * 'a binaryTree
```

or

```
type 'a binaryTree = 
  | Leaf of 'a
  | Node of 'a binaryTree * 'a binaryTree
```
depending on where you want to store the data.

People that use the first type often don't show the leafs (nil) ... but they technically exist

**Comment by Amxx** [comment]
Anyway, people have been fighting over tree nomenclature for decades. AFAIK, I use the one from Thomas Cormen's Introduction to Algorithms (very good read).

I understand other people use different names for some particular structures (and honestly, translation doesn't help here).

The real question is: is there anything unclear about the library and how the merklee trees are sorted ? If yes we should address that ! If its just about being pedantic, I can see how people would propose back and forward changes, and that is not bringing much value IMO.

**Comment by frangio** [comment]
Because of the overloaded terminology the readme links to a definition on [nist.gov](https://xlinux.nist.gov/dads/HTML/completeBinaryTree.html), which for [binary tree](https://xlinux.nist.gov/dads/HTML/binarytree.html) says:

>Definition: A [tree](https://xlinux.nist.gov/dads/HTML/tree.html) with at most two [children](https://xlinux.nist.gov/dads/HTML/child.html) for each [node](https://xlinux.nist.gov/dads/HTML/node.html).
>
>Formal Definition: A binary tree either
>
> - is empty (no nodes), or
> - has a [root](https://xlinux.nist.gov/dads/HTML/root.html) node, a left binary tree, and a right binary tree.

The Definition line is ambiguous, but the "Formal Definition" unambiguously defines binary tree nodes as having either 0 or 2 children. This means that the tree shared by @gc-garcol [above](https://github.com/OpenZeppelin/merkle-tree/pull/20#issuecomment-1540815771) is not binary according to the definition we're using in this library.

**Comment by n-tread** [comment]
@frangio if you re-read the Formal Definition that you quoted carefully, I think you'll see it admits trees where each node has 0, 1, or 2 children :)

Take the tree shared by @gc-garcol as an example. Node `#3` with 1 child:
* has a root node
* has a left binary tree composed of node `#6`
* has a right binary tree which is empty (no nodes)

Thus the Definition and Formal Definition agree with each other and do not contradict each other… after all there is nothing ambiguous about “at most two children for each node.”

You also linked to nist's [complete binary tree](https://xlinux.nist.gov/dads/HTML/completeBinaryTree.html) definition which also admits these types of trees, including the one shared by @gc-garcol above.

Also FWIW @Amxx I didn't find an explicit definition in Thomas Cormen's Introduction to Algorithms, but the book includes many diagrams of binary trees with single-children nodes. Here are a couple (from the [Third Edition](https://github.com/calvint/AlgorithmsOneProblems/blob/master/Algorithms/Thomas%20H.%20Cormen,%20Charles%20E.%20Leiserson,%20Ronald%20L.%20Rivest,%20Clifford%20Stein%20Introduction%20to%20Algorithms,%20Third%20Edition%20%202009.pdf)) — and it's clear from the context that there are no “invisible leaves” here:

Screenshot 2024-09-13 at 00 54 28
Screenshot 2024-09-13 at 00 49 35

More to the point, the reason I got interested in this is that I'm trying to understand which types of trees your library handles correctly. From what I can tell, the algorithm in [makeMerkleTree](https://github.com/OpenZeppelin/merkle-tree/blob/31c37cf3f37a6e8022cfa661a290d9879bb31b71/src/core.ts#L19-L34) is actually, surprisingly, able to handle any complete binary trees just fine (i.e. any positive integer number of leaves) regardless of whether the nodes have 0, 1, or 2 children. It seems like you also have [test coverage](https://github.com/OpenZeppelin/merkle-tree/blob/31c37cf3f37a6e8022cfa661a290d9879bb31b71/src/standard.test.ts#L11) to this effect. Maybe it was a happy accident ;)

**Comment by Amxx** [comment]
Not an happy accident.

Despite all the discussion on terminology, we don't want to reject sets of leaves because the number of value is "not right"

This library really is about representing a "set of value" using a succinct representation (the root of the tree) and a inclusion proof. We feel like the actual structure/shape of the tree is irrelevant... as long as all sets can be encoded, and all elements in these sets can be proven with "succinct" proofs.

That is why we "force" the shape of the tree. How anyone names that shape is not essential IMO

**Comment by frangio** [comment]
> @frangio if you re-read the Formal Definition that you quoted carefully, I think you'll see it admits trees where each node has 0, 1, or 2 children :)

I stand corrected! I don't know what I was thinking, it seems obvious to me now.

**Pull request closed without merging**
