### PR TITLE
Introduce SimpleMerkleTree & migrate to ethers.js

### LINKED ISSUE #13: Customize leaf hash function
https://github.com/OpenZeppelin/merkle-tree/blob/b3d988984debfd6c951b8f1799982f191ff5b792/src/standard.ts#L9

In the provided example, the desired algorithm for getting leaves is:

bytes32 leaf = keccak256(bytes.concat(keccak256(abi.encode(addr, amount))));

And this works perfectly fine when there is more than 1 value inside the leaf.

However, when the value inside the leaf is singular, then there is no need for extra concat and keccak256, it only makes gas overhead. And the preferred algorithm is:

bytes32 leaf = keccak256(abi.encodePacked(addr));

This makes make a big difference because there is no possibility to change the leaf algorithm that this library uses, hence all trees and proofs for them can't be synced with the contract's behavior.

### LINKED ISSUE #30: Compare bytes does not correctly compare array of different length
See: https://github.com/OpenZeppelin/merkle-tree/blob/0951d3ca036d44c61e33fd9731750cf0ce2978c3/src/bytes.ts#L5

Bytes are compared from left to right, this means

`0xff` is considered greater than `0x0100` ... because the first byte `0xff` is bigger than the first byte `0x01`.

Function is correct for arrays of equal size, which is always the case in this libary (always used with 32bytes).

### PR DESCRIPTION
**Pull request by Amxx**
Fixes #30
Partially Fixes #13   

### This PR:

- Replaces previous tooling with ethers.js
  - Core now support BytesLike (hex strings and Uint8Arrays)
  - All values are returnes as hex strings (proofs, leaf hashes, ...)
- Fixe the Bytes (now BytesLike) compare function. (See #30)
- Introduce a SimpleMerkleTree (in parallele to the existing StandardMerkleTree) 
  - No encoding
  - Leafs are all BytesLike with length 32bytes
  - Provides the same interface as StandardMerkleTree, with the exception of `leafHash` which is irrelevant
  - This can be used to in conjunction with a custom hashing function to represent trees that don't do the recommanded double hashing.
  
### Rational:

Merkle tree have been built using other tools before this library was available. Some of these trees do not use double hashing, and are thus not representable using the existing `StandardMerkleTree` class. This prevents devs that have to deal with these trees from using this library.
The goal is NOT to encourage not using double hashes. StandardMerkleTree should be prefered for new trees. The goal is to provide a migration path to user that would want to manipulate old trees with this new library.
  
### TODO
- [ ] Documentation

### CODE REVIEW

**Comment by frangio** [comment]
Using the ethers package increases the installation size from 7.2M to 24M... I would not do that. It's heavy and a lot of people are using Viem now, so I think it would be better for this library to stay agnostic.

We can install the bytes utilities only with the package `@ethersproject/bytes`. Note that it's Ethers v5 code but it should be fine.

**Comment by Amxx** [comment]
Is there an easy way to check the install size of a package you are working on ?

**Comment by frangio** [comment]
Not that I know of. I did `npm pack` and then installed the tarball in a fresh directory after `npm init -y`.

---

Is there an issue with native bigint?

**Comment by Amxx** [comment]
Replaced by #36

**Pull request closed without merging**
