### PR TITLE
Add verify functions

### LINKED ISSUE #8: No Verify method
Hope that JS can implement the Verify method of Merkle

### PR DESCRIPTION
**Pull request by frangio**
Fixes #8

### CODE REVIEW

**Comment by Amxx** [comment]
`getProof` and `getMultiProof` automatically verify the proofs that they produced. IMO, this should be done using these new functions.

Otherwize looks good.

**Comment by Amxx** [comment]
For `getProof` the change is quite simple:

```diff
     // check proof
-    const hash = this.tree[treeIndex]!;
-    const impliedRoot = processProof(hash, proof);
-    if (!equalsBytes(impliedRoot, this.tree[0]!)) {
+    if (!this.verify(leaf, proof.map(bytesToHex))) {
       throw new Error('Unable to prove value');
     }
```

But for `getMultiProof` its quite more complex because we need the leaves in `T` format
```diff
     // check proof
-    const impliedRoot = processMultiProof(proof);
-    if (!equalsBytes(impliedRoot, this.tree[0]!)) {
+    if (!this.verifyMultiProof({
+      leaves: indices.map(i => this.values.find(e => e.treeIndex == i)!.value),
+      proof: proof.proof.map(bytesToHex),
+      proofFlags: proof.proofFlags,
+    })) {
       throw new Error('Unable to prove values');
     }
```

**Comment by frangio** [comment]
I implemented that suggestion but I refactored the code a little to avoid converting back and forth between string and Bytes.

**Review by Amxx — APPROVED** [review]
LGTM,

Just wondering is the `_verify` and `_verifyMultiProof` should be marked as private

**Comment by frangio** [comment]
Do you mean that maybe they shouldn't be private? Let's keep them private for now because they work on Bytes values and not on strings like the rest of the StandardMerkleTree interface.

Eventually I would be interested in making standard and core both work generically on both Bytes and strings.

**Comment by Amxx** [comment]
> Do you mean that maybe they shouldn't be private?

I meant they should be private, which they are. My bad.

**Comment by Amxx** [comment]
> Eventually I would be interested in making standard and core both work generically on both Bytes and strings.

I know we don't like dependencies, but IMO there is already a de-facto standard for that:
https://github.com/ethers-io/ethers.js/blob/master/packages/bytes/src.ts/index.ts#L12

**Comment by duktig666** [comment]
Can I directly call a similar method in JS and keep it consistent with solidity

solidity Provides such a method


```
function verify(bytes32[] memory proof, bytes32 root, bytes32 leaf) internal pure returns (bool) {
    return processProof(proof, leaf) == root;
}
```

https://github.com/merkletreejs/merkletreejs/blob/master/src/MerkleTree.ts
也实现了类似的方法：
```
verify (proof: any[], targetNode: Buffer | string, root: Buffer | string):boolean {

}
```

```
const tree = StandardMerkleTree.of();
```

Can Tree call `verify` directly?

**Comment by duktig666** [comment]
> 

tree. verify();

**Pull request merged**
